#!/usr/bin/env bash
set -e

echo "Working directory: $(pwd)"
echo "Listing wheels: $(ls -la target/weels/)"
echo "Installing"
uv sync --no-install-project --dev
uv pip install archive-to-parquet --find-links=target/wheels/ --verbose --only-binary=true
uv run --no-sync pytest
