#!/usr/bin/env bash
set -e
set -x

echo "Working directory: $(pwd)"
echo "Listing wheels:"
ls -la target/wheels/
echo "Installing Rust"

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
. "$HOME/.cargo/env"

pip install -U uv

uv sync --no-install-project --dev --link-mode=copy
uv pip install archive-to-parquet --find-links=target/wheels/ --verbose --only-binary=true
uv run --no-sync pytest
