on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ghcr.io/rust-cross/manylinux_2_28-cross:x86_64
            target: x86_64-unknown-linux-gnu
          - image: ghcr.io/rust-cross/manylinux_2_28-cross:aarch64
            target: aarch64-unknown-linux-gnu
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
      - run: apt install -y zstd
      - uses: jdx/mise-action@v2
        with:
          install: "false"
          cache: "true"
          cache_key_prefix: 'mise-v0-python-'
          mise_toml: |
            [tools]
            uv = "latest"
            "pipx:maturin" = {version = "latest", extras = "zig" }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: mise --version
      - run: mise x -- maturin build --target=${{matrix.target}} --compatibility=manylinux_2_24
