on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main
    steps:
      - uses: actions/checkout@v4
      - run: apt install -y zstd
      - uses: jdx/mise-action@v2
        with:
          install: "true"
          cache: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mise --version
